services:
  postgres-catalog:
    image: postgres:18-alpine
    container_name: music-catalog-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    volumes:
      - postgres_catalog_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network
  catalog-service:
    build:
      context: .  
      dockerfile: cmd/catalog-service/Dockerfile
    container_name: music-service-catalog
    environment:
      CATALOG_DB_HOST: postgres-catalog
    env_file:
      - .env
    ports:
      - "50053:50053"
    depends_on:
      postgres-catalog:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped
  postgres-auth:
    image: postgres:18-alpine
    container_name: music-auth-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network

  auth-service:
    build:
      context: .
      dockerfile: cmd/auth-service/Dockerfile
    container_name: music-auth-service
    environment:
      AUTH_DB_HOST: postgres-auth
    env_file:
      - .env
    ports:
      - "50051:50051"
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped

networks:
  music-network:
    driver: bridge

volumes:
  postgres_catalog_data:
  postgres_auth_data: