services:
  postgres-catalog:
    image: postgres:18-alpine
    container_name: music-catalog-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    volumes:
      - postgres_catalog_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network
  catalog-service:
    build:
      context: .  
      dockerfile: cmd/catalog-service/Dockerfile
    container_name: music-service-catalog
    environment:
      CATALOG_DB_HOST: postgres-catalog
    env_file:
      - .env
    ports:
      - "50053:50053"
    depends_on:
      postgres-catalog:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped
  postgres-auth:
    image: postgres:18-alpine
    container_name: music-auth-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network

  auth-service:
    build:
      context: .
      dockerfile: cmd/auth-service/Dockerfile
    container_name: music-auth-service
    environment:
      AUTH_DB_HOST: postgres-auth
    env_file:
      - .env
    ports:
      - "50051:50051"
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped
  postgres-file:
    image: postgres:18-alpine
    container_name: music-file-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: file_user
      POSTGRES_PASSWORD: file_pass
      POSTGRES_DB: file_db
    volumes:
      - postgres_file_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U file_user -d file_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network
  minio:
    image: minio/minio
    container_name: music-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - music-network
  file-service:
    build:
      context: .
      dockerfile: cmd/file-service/Dockerfile
    container_name: music-file-service
    environment:
      FILE_DB_HOST: postgres-file
    env_file:
      - .env
    ports:
      - "50052:50052"
    depends_on:
      postgres-file:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped
  postgres-playlist:
    image: postgres:18-alpine
    container_name: music-playlist-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: playlist_user
      POSTGRES_PASSWORD: playlist_pass
      POSTGRES_DB: playlist_db
    volumes:
      - postgres_playlist_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U playlist_user -d playlist_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network

  playlist-service:
    build:
      context: .
      dockerfile: cmd/playlist-service/Dockerfile
    container_name: music-playlist-service
    environment:
      PLAYLIST_DB_HOST: postgres-playlist
    env_file:
      - .env
    ports:
      - "50054:50054"
    depends_on:
      postgres-playlist:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped
  postgres-rules:
    image: postgres:18-alpine
    container_name: music-rules-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: rules_user
      POSTGRES_PASSWORD: rules_pass
      POSTGRES_DB: rules_db
    volumes:
      - postgres_rules_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rules_user -d rules_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-network
  rules-service:
    build:
      context: .
      dockerfile: cmd/rules-service/Dockerfile
    container_name: music-rules-service
    environment:
      RULES_DB_HOST: postgres-rules
    env_file:
      - .env
    ports:
      - "50055:50055"
    depends_on:
      postgres-rules:
        condition: service_healthy
    networks:
      - music-network
    restart: unless-stopped
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: music-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - catalog-service
      - auth-service
      - file-service
      - playlist-service
      - rules-service
    networks:
      - music-network
    restart: unless-stopped
networks:
  music-network:
    driver: bridge

volumes:
  postgres_catalog_data:
  postgres_auth_data:
  postgres_file_data:
  minio_data:
  postgres_playlist_data:
  postgres_rules_data: